//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suscriptores
    {
        public int id { get; set; }
        public string nombre_completo { get; set; }
        public string direccion { get; set; }
        public string barrio { get; set; }
        public int consumo { get; set; }
        public int id_estrato { get; set; }
    
        public virtual estratos estratos { get; set; }
    }
}
